### ISSUE TITLE
is this lib alive

### ISSUE THREAD

**Issue by hhhaiai** [Surge1223/adb-arm-1.0.37#3]
hello, @Surge1223
Is the library still maintained

**Comment by Surge1223** [comment]
No, this was actually meant to be built on device if I recall correctly.  Which it did, this repo might be confusing because it's the same vers of adb as one of the arm64 and arm adb binary zips I uploaded.

The source for adb from 1.0.37 to now is vastly changed. I'm not sure what the current efforts for newer adb sources for arm/arm64 are.
